[package]
name = "downsample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = { version = "*", features = ["decompress", "sort_multiple", "is_in"] }
clap = "*"
